// Generated by scripts/prepare-product-galleries.mjs.
// Source images remain in the private Codex English ecommerce output folders.

export const productGalleries: Record<string, readonly string[]> = {
  "bmw-5-series-screen-protectors": [
    "/catalog/gallery-bmw-5-screen-protectors-view-02.jpg",
    "/catalog/gallery-bmw-5-screen-protectors-view-03.jpg",
    "/catalog/gallery-bmw-5-screen-protectors-view-04.jpg",
    "/catalog/gallery-bmw-5-screen-protectors-view-05.jpg"
  ],
  "bmw-multi-series-screen-protectors": [
    "/catalog/gallery-bmw-multi-screen-protectors-view-02.jpg",
    "/catalog/gallery-bmw-multi-screen-protectors-view-03.jpg",
    "/catalog/gallery-bmw-multi-screen-protectors-view-04.jpg",
    "/catalog/gallery-bmw-multi-screen-protectors-view-05.jpg"
  ],
  "bmw-x1-ix1-integrated-display-screen-protector": [
    "/catalog/gallery-bmw-x1-ix1-screen-protector-view-02.jpg",
    "/catalog/gallery-bmw-x1-ix1-screen-protector-view-03.jpg",
    "/catalog/gallery-bmw-x1-ix1-screen-protector-view-04.jpg",
    "/catalog/gallery-bmw-x1-ix1-screen-protector-view-05.jpg"
  ],
  "bmw-x3-x4-screen-protectors": [
    "/catalog/gallery-bmw-x3-x4-screen-protectors-view-02.jpg",
    "/catalog/gallery-bmw-x3-x4-screen-protectors-view-03.jpg",
    "/catalog/gallery-bmw-x3-x4-screen-protectors-view-04.jpg",
    "/catalog/gallery-bmw-x3-x4-screen-protectors-view-05.jpg"
  ],
  "byd-seal-screen-protectors": [
    "/catalog/gallery-byd-seal-screen-protectors-view-02.jpg",
    "/catalog/gallery-byd-seal-screen-protectors-view-03.jpg",
    "/catalog/gallery-byd-seal-screen-protectors-view-04.jpg",
    "/catalog/gallery-byd-seal-screen-protectors-view-05.jpg"
  ],
  "dji-pocket-4-silicone-cover-4-piece": [
    "/catalog/gallery-dji-pocket-4-cover-4-piece-view-02.jpg",
    "/catalog/gallery-dji-pocket-4-cover-4-piece-view-03.jpg",
    "/catalog/gallery-dji-pocket-4-cover-4-piece-view-04.jpg",
    "/catalog/gallery-dji-pocket-4-cover-4-piece-view-05.jpg"
  ],
  "dji-pocket-4-silicone-cover-6-piece": [
    "/catalog/gallery-dji-pocket-4-cover-6-piece-view-02.jpg",
    "/catalog/gallery-dji-pocket-4-cover-6-piece-view-03.jpg",
    "/catalog/gallery-dji-pocket-4-cover-6-piece-view-04.jpg",
    "/catalog/gallery-dji-pocket-4-cover-6-piece-view-05.jpg"
  ],
  "ford-mustang-mach-e-panoramic-roof-sunshade": [
    "/catalog/gallery-mustang-mach-e-roof-sunshade-view-02.jpg",
    "/catalog/gallery-mustang-mach-e-roof-sunshade-view-03.jpg",
    "/catalog/gallery-mustang-mach-e-roof-sunshade-view-04.jpg",
    "/catalog/gallery-mustang-mach-e-roof-sunshade-view-05.jpg"
  ],
  "geely-galaxy-e5-ex5-screen-protector": [
    "/catalog/gallery-geely-galaxy-screen-protector-view-02.jpg",
    "/catalog/gallery-geely-galaxy-screen-protector-view-03.jpg",
    "/catalog/gallery-geely-galaxy-screen-protector-view-04.jpg"
  ],
  "geely-xingyuan-2025-rhd-display-protectors": [
    "/catalog/gallery-geely-xingyuan-screen-protectors-view-02.jpg",
    "/catalog/gallery-geely-xingyuan-screen-protectors-view-03.jpg",
    "/catalog/gallery-geely-xingyuan-screen-protectors-view-04.jpg",
    "/catalog/gallery-geely-xingyuan-screen-protectors-view-05.jpg"
  ],
  "magnetic-mesh-car-window-shade-set": [
    "/catalog/gallery-magnetic-window-shades-view-02.jpg",
    "/catalog/gallery-magnetic-window-shades-view-03.jpg",
    "/catalog/gallery-magnetic-window-shades-view-04.jpg",
    "/catalog/gallery-magnetic-window-shades-view-05.jpg"
  ],
  "mini-model-specific-screen-protectors": [
    "/catalog/gallery-mini-screen-protectors-view-02.jpg",
    "/catalog/gallery-mini-screen-protectors-view-03.jpg",
    "/catalog/gallery-mini-screen-protectors-view-04.jpg",
    "/catalog/gallery-mini-screen-protectors-view-05.jpg"
  ],
  "pt75-151w-retractable-car-charger": [
    "/catalog/gallery-retractable-car-charger-view-02.jpg",
    "/catalog/gallery-retractable-car-charger-view-03.jpg",
    "/catalog/gallery-retractable-car-charger-view-04.jpg",
    "/catalog/gallery-retractable-car-charger-view-05.jpg"
  ],
  "rivian-r2-drawer-organizer": [
    "/catalog/gallery-rivian-r2-drawer-organizer-view-02.jpg",
    "/catalog/gallery-rivian-r2-drawer-organizer-view-03.jpg",
    "/catalog/gallery-rivian-r2-drawer-organizer-view-04.jpg",
    "/catalog/gallery-rivian-r2-drawer-organizer-view-05.jpg"
  ],
  "starlink-mini-silicone-cover": [
    "/catalog/gallery-starlink-mini-cover-view-02.jpg",
    "/catalog/gallery-starlink-mini-cover-view-03.jpg",
    "/catalog/gallery-starlink-mini-cover-view-04.jpg",
    "/catalog/gallery-starlink-mini-cover-view-05.jpg"
  ],
  "starlink-standard-gen3-silicone-cover": [
    "/catalog/gallery-starlink-gen3-cover-view-02.jpg",
    "/catalog/gallery-starlink-gen3-cover-view-03.jpg",
    "/catalog/gallery-starlink-gen3-cover-view-04.jpg",
    "/catalog/gallery-starlink-gen3-cover-view-05.jpg"
  ],
  "tesla-center-console-storage-box-set": [
    "/catalog/gallery-center-console-storage-view-02.jpg",
    "/catalog/gallery-center-console-storage-view-03.jpg",
    "/catalog/gallery-center-console-storage-view-04.jpg",
    "/catalog/gallery-center-console-storage-view-05.jpg"
  ],
  "tesla-model-3-y-retractable-console-charging-hub": [
    "/catalog/gallery-tesla-model-3-y-retractable-console-charging-hub-view-02.jpg",
    "/catalog/gallery-tesla-model-3-y-retractable-console-charging-hub-view-03.jpg",
    "/catalog/gallery-tesla-model-3-y-retractable-console-charging-hub-view-04.jpg",
    "/catalog/gallery-tesla-model-3-y-retractable-console-charging-hub-view-05.jpg",
    "/catalog/gallery-tesla-model-3-y-retractable-console-charging-hub-view-06.jpg",
    "/catalog/gallery-tesla-model-3-y-retractable-console-charging-hub-view-07.jpg",
    "/catalog/gallery-tesla-model-3-y-retractable-console-charging-hub-view-08.jpg"
  ],
  "tesla-model-3-y-rear-vent-charging-hub": [
    "/catalog/gallery-tesla-model-3-y-rear-vent-charging-hub-view-02.jpg",
    "/catalog/gallery-tesla-model-3-y-rear-vent-charging-hub-view-03.jpg",
    "/catalog/gallery-tesla-model-3-y-rear-vent-charging-hub-view-04.jpg",
    "/catalog/gallery-tesla-model-3-y-rear-vent-charging-hub-view-05.jpg",
    "/catalog/gallery-tesla-model-3-y-rear-vent-charging-hub-view-06.jpg",
    "/catalog/gallery-tesla-model-3-y-rear-vent-charging-hub-view-07.jpg"
  ],
  "tesla-cybertruck-panoramic-roof-sunshade": [
    "/catalog/gallery-cybertruck-roof-sunshade-view-02.jpg",
    "/catalog/gallery-cybertruck-roof-sunshade-view-03.jpg",
    "/catalog/gallery-cybertruck-roof-sunshade-view-04.jpg",
    "/catalog/gallery-cybertruck-roof-sunshade-view-05.jpg"
  ],
  "tesla-cybertruck-screen-protectors": [
    "/catalog/gallery-cybertruck-screen-protectors-view-02.jpg",
    "/catalog/gallery-cybertruck-screen-protectors-view-03.jpg",
    "/catalog/gallery-cybertruck-screen-protectors-view-04.jpg",
    "/catalog/gallery-cybertruck-screen-protectors-view-05.jpg"
  ],
  "tesla-dashboard-dual-layer-storage-tray": [
    "/catalog/gallery-dashboard-storage-tray-view-02.jpg",
    "/catalog/gallery-dashboard-storage-tray-view-03.jpg",
    "/catalog/gallery-dashboard-storage-tray-view-04.jpg",
    "/catalog/gallery-dashboard-storage-tray-view-05.jpg"
  ],
  "tesla-display-edge-clip-on-phone-holder": [
    "/catalog/gallery-display-clip-phone-holder-view-02.jpg",
    "/catalog/gallery-display-clip-phone-holder-view-03.jpg",
    "/catalog/gallery-display-clip-phone-holder-view-04.jpg",
    "/catalog/gallery-display-clip-phone-holder-view-05.jpg"
  ],
  "tesla-display-mount-flower-aroma-accessory": [
    "/catalog/gallery-display-mount-aroma-view-02.jpg",
    "/catalog/gallery-display-mount-aroma-view-03.jpg",
    "/catalog/gallery-display-mount-aroma-view-04.jpg",
    "/catalog/gallery-display-mount-aroma-view-05.jpg"
  ],
  "tesla-door-handle-trim-set": [
    "/catalog/gallery-door-handle-trim-view-02.jpg",
    "/catalog/gallery-door-handle-trim-view-03.jpg",
    "/catalog/gallery-door-handle-trim-view-04.jpg",
    "/catalog/gallery-door-handle-trim-view-05.jpg"
  ],
  "tesla-door-striker-check-covers": [
    "/catalog/gallery-door-striker-covers-view-02.jpg",
    "/catalog/gallery-door-striker-covers-view-03.jpg",
    "/catalog/gallery-door-striker-covers-view-04.jpg",
    "/catalog/gallery-door-striker-covers-view-05.jpg"
  ],
  "tesla-foldable-car-desk": [
    "/catalog/gallery-foldable-car-desk-view-02.jpg",
    "/catalog/gallery-foldable-car-desk-view-03.jpg",
    "/catalog/gallery-foldable-car-desk-view-04.jpg",
    "/catalog/gallery-foldable-car-desk-view-05.jpg"
  ],
  "tesla-foldable-seat-back-hook": [
    "/catalog/gallery-foldable-seat-back-hook-view-02.jpg",
    "/catalog/gallery-foldable-seat-back-hook-view-03.jpg",
    "/catalog/gallery-foldable-seat-back-hook-view-04.jpg",
    "/catalog/gallery-foldable-seat-back-hook-view-05.jpg"
  ],
  "tesla-glovebox-hook-set": [
    "/catalog/gallery-glovebox-hooks-view-02.jpg",
    "/catalog/gallery-glovebox-hooks-view-03.jpg",
    "/catalog/gallery-glovebox-hooks-view-04.jpg",
    "/catalog/gallery-glovebox-hooks-view-05.jpg"
  ],
  "tesla-hidden-armrest-storage-box": [
    "/catalog/gallery-armrest-hidden-storage-view-02.jpg",
    "/catalog/gallery-armrest-hidden-storage-view-03.jpg",
    "/catalog/gallery-armrest-hidden-storage-view-04.jpg",
    "/catalog/gallery-armrest-hidden-storage-view-05.jpg"
  ],
  "tesla-model-3-2019-2022-screen-protector": [
    "/catalog/gallery-model-3-legacy-display-protectors-view-02.jpg",
    "/catalog/gallery-model-3-legacy-display-protectors-view-03.jpg",
    "/catalog/gallery-model-3-legacy-display-protectors-view-04.jpg",
    "/catalog/gallery-model-3-legacy-display-protectors-view-05.jpg"
  ],
  "tesla-model-3-highland-control-panel-soft-film": [
    "/catalog/gallery-model-3-control-panel-films-view-02.jpg",
    "/catalog/gallery-model-3-control-panel-films-view-03.jpg",
    "/catalog/gallery-model-3-control-panel-films-view-04.jpg",
    "/catalog/gallery-model-3-control-panel-films-view-05.jpg"
  ],
  "tesla-model-3-highland-display-protectors": [
    "/catalog/gallery-model-3-highland-display-protectors-view-02.jpg",
    "/catalog/gallery-model-3-highland-display-protectors-view-03.jpg",
    "/catalog/gallery-model-3-highland-display-protectors-view-04.jpg",
    "/catalog/gallery-model-3-highland-display-protectors-view-05.jpg"
  ],
  "tesla-model-3-y-behind-screen-etc-storage-tray": [
    "/catalog/gallery-behind-screen-etc-tray-view-02.jpg",
    "/catalog/gallery-behind-screen-etc-tray-view-03.jpg",
    "/catalog/gallery-behind-screen-etc-tray-view-04.jpg",
    "/catalog/gallery-behind-screen-etc-tray-view-05.jpg"
  ],
  "tesla-model-3-y-clip-on-air-vent-phone-holder": [
    "/catalog/gallery-air-vent-phone-holder-view-02.jpg",
    "/catalog/gallery-air-vent-phone-holder-view-03.jpg",
    "/catalog/gallery-air-vent-phone-holder-view-04.jpg",
    "/catalog/gallery-air-vent-phone-holder-view-05.jpg"
  ],
  "tesla-model-3-y-tpe-seat-gap-storage-box-set": [
    "/catalog/gallery-seat-gap-storage-view-02.jpg",
    "/catalog/gallery-seat-gap-storage-view-03.jpg",
    "/catalog/gallery-seat-gap-storage-view-04.jpg",
    "/catalog/gallery-seat-gap-storage-view-05.jpg"
  ],
  "tesla-model-y-3-yl-diamond-console-panel-covers": [
    "/catalog/gallery-diamond-console-covers-view-02.jpg",
    "/catalog/gallery-diamond-console-covers-view-03.jpg",
    "/catalog/gallery-diamond-console-covers-view-04.jpg",
    "/catalog/gallery-diamond-console-covers-view-05.jpg"
  ],
  "tesla-model-y-cup-holder-inserts": [
    "/catalog/gallery-model-y-cup-holder-inserts-view-02.jpg",
    "/catalog/gallery-model-y-cup-holder-inserts-view-03.jpg",
    "/catalog/gallery-model-y-cup-holder-inserts-view-04.jpg",
    "/catalog/gallery-model-y-cup-holder-inserts-view-05.jpg"
  ],
  "tesla-model-y-juniper-tpe-floor-mats": [
    "/catalog/gallery-model-y-juniper-floor-mats-view-02.jpg",
    "/catalog/gallery-model-y-juniper-floor-mats-view-03.jpg",
    "/catalog/gallery-model-y-juniper-floor-mats-view-04.jpg",
    "/catalog/gallery-model-y-juniper-floor-mats-view-05.jpg"
  ],
  "tesla-model-y-lower-console-organizer": [
    "/catalog/gallery-model-y-lower-console-view-02.jpg",
    "/catalog/gallery-model-y-lower-console-view-03.jpg",
    "/catalog/gallery-model-y-lower-console-view-04.jpg",
    "/catalog/gallery-model-y-lower-console-view-05.jpg"
  ],
  "tesla-model-y-standard-console-cup-holder-organizer": [
    "/catalog/gallery-model-y-console-cup-holder-view-02.jpg",
    "/catalog/gallery-model-y-console-cup-holder-view-03.jpg",
    "/catalog/gallery-model-y-console-cup-holder-view-04.jpg",
    "/catalog/gallery-model-y-console-cup-holder-view-05.jpg"
  ],
  "tesla-model-y-standard-rear-center-storage-box": [
    "/catalog/gallery-model-y-rear-center-storage-view-02.jpg",
    "/catalog/gallery-model-y-rear-center-storage-view-03.jpg",
    "/catalog/gallery-model-y-rear-center-storage-view-04.jpg",
    "/catalog/gallery-model-y-rear-center-storage-view-05.jpg"
  ],
  "tesla-model-y-yl-center-rear-screen-protectors": [
    "/catalog/gallery-tesla-center-rear-screen-protectors-view-02.jpg",
    "/catalog/gallery-tesla-center-rear-screen-protectors-view-03.jpg",
    "/catalog/gallery-tesla-center-rear-screen-protectors-view-04.jpg",
    "/catalog/gallery-tesla-center-rear-screen-protectors-view-05.jpg"
  ],
  "tesla-model-y-yl-eyeglass-case-cup-holder": [
    "/catalog/gallery-eyeglass-case-cup-holder-view-02.jpg",
    "/catalog/gallery-eyeglass-case-cup-holder-view-03.jpg",
    "/catalog/gallery-eyeglass-case-cup-holder-view-04.jpg",
    "/catalog/gallery-eyeglass-case-cup-holder-view-05.jpg"
  ],
  "tesla-model-y-yl-hidden-trunk-hooks": [
    "/catalog/gallery-hidden-trunk-hooks-view-02.jpg",
    "/catalog/gallery-hidden-trunk-hooks-view-03.jpg",
    "/catalog/gallery-hidden-trunk-hooks-view-04.jpg",
    "/catalog/gallery-hidden-trunk-hooks-view-05.jpg"
  ],
  "tesla-model-y-yl-screen-protector": [
    "/catalog/gallery-dust-free-screen-kit-view-02.jpg",
    "/catalog/gallery-dust-free-screen-kit-view-03.jpg",
    "/catalog/gallery-dust-free-screen-kit-view-04.jpg",
    "/catalog/gallery-dust-free-screen-kit-view-05.jpg"
  ],
  "tesla-model-yl-front-rear-screen-protector-options": [
    "/catalog/gallery-tesla-center-rear-screen-protectors-view-02.jpg",
    "/catalog/gallery-tesla-center-rear-screen-protectors-view-03.jpg",
    "/catalog/gallery-tesla-center-rear-screen-protectors-view-04.jpg",
    "/catalog/gallery-tesla-center-rear-screen-protectors-view-05.jpg"
  ],
  "tesla-model-yl-metal-heel-plate-tpe-floor-mats": [
    "/catalog/gallery-metal-heel-floor-mats-view-02.jpg",
    "/catalog/gallery-metal-heel-floor-mats-view-03.jpg",
    "/catalog/gallery-metal-heel-floor-mats-view-04.jpg",
    "/catalog/gallery-metal-heel-floor-mats-view-05.jpg"
  ],
  "tesla-model-yl-rear-console-storage-bin": [
    "/catalog/gallery-model-yl-rear-console-view-02.jpg",
    "/catalog/gallery-model-yl-rear-console-view-03.jpg",
    "/catalog/gallery-model-yl-rear-console-view-04.jpg",
    "/catalog/gallery-model-yl-rear-console-view-05.jpg"
  ],
  "tesla-model-yl-second-row-vent-hooks": [
    "/catalog/gallery-second-row-vent-hooks-view-02.jpg",
    "/catalog/gallery-second-row-vent-hooks-view-03.jpg",
    "/catalog/gallery-second-row-vent-hooks-view-04.jpg",
    "/catalog/gallery-second-row-vent-hooks-view-05.jpg"
  ],
  "tesla-model-yl-trunk-protector-collection": [
    "/catalog/gallery-model-yl-trunk-protection-view-02.jpg",
    "/catalog/gallery-model-yl-trunk-protection-view-03.jpg",
    "/catalog/gallery-model-yl-trunk-protection-view-04.jpg",
    "/catalog/gallery-model-yl-trunk-protection-view-05.jpg"
  ],
  "tesla-model-yl-under-seat-storage-box": [
    "/catalog/gallery-model-yl-under-seat-storage-view-02.jpg",
    "/catalog/gallery-model-yl-under-seat-storage-view-03.jpg",
    "/catalog/gallery-model-yl-under-seat-storage-view-04.jpg",
    "/catalog/gallery-model-yl-under-seat-storage-view-05.jpg"
  ],
  "tesla-new-car-protection-bundle": [
    "/catalog/gallery-new-car-protection-bundle-view-02.jpg",
    "/catalog/gallery-new-car-protection-bundle-view-03.jpg",
    "/catalog/gallery-new-car-protection-bundle-view-04.jpg",
    "/catalog/gallery-new-car-protection-bundle-view-05.jpg"
  ],
  "tesla-no-drill-mud-flaps": [
    "/catalog/gallery-no-drill-mud-flaps-view-02.jpg",
    "/catalog/gallery-no-drill-mud-flaps-view-03.jpg",
    "/catalog/gallery-no-drill-mud-flaps-view-04.jpg",
    "/catalog/gallery-no-drill-mud-flaps-view-05.jpg"
  ],
  "tesla-rear-air-vent-protective-frame": [
    "/catalog/gallery-rear-air-vent-frame-view-02.jpg",
    "/catalog/gallery-rear-air-vent-frame-view-03.jpg",
    "/catalog/gallery-rear-air-vent-frame-view-04.jpg",
    "/catalog/gallery-rear-air-vent-frame-view-05.jpg"
  ],
  "tesla-rear-headrest-hook-pair": [
    "/catalog/gallery-rear-headrest-hooks-view-02.jpg",
    "/catalog/gallery-rear-headrest-hooks-view-03.jpg",
    "/catalog/gallery-rear-headrest-hooks-view-04.jpg",
    "/catalog/gallery-rear-headrest-hooks-view-05.jpg"
  ],
  "tesla-rear-seat-phone-tablet-holder": [
    "/catalog/gallery-rear-seat-device-holder-view-02.jpg",
    "/catalog/gallery-rear-seat-device-holder-view-03.jpg",
    "/catalog/gallery-rear-seat-device-holder-view-04.jpg",
    "/catalog/gallery-rear-seat-device-holder-view-05.jpg"
  ],
  "tesla-rearview-mirror-silicone-cover": [
    "/catalog/gallery-rearview-mirror-cover-view-02.jpg",
    "/catalog/gallery-rearview-mirror-cover-view-03.jpg",
    "/catalog/gallery-rearview-mirror-cover-view-04.jpg",
    "/catalog/gallery-rearview-mirror-cover-view-05.jpg"
  ],
  "tesla-silicone-display-frame": [
    "/catalog/gallery-silicone-display-frame-view-02.jpg",
    "/catalog/gallery-silicone-display-frame-view-03.jpg",
    "/catalog/gallery-silicone-display-frame-view-04.jpg",
    "/catalog/gallery-silicone-display-frame-view-05.jpg"
  ],
  "tesla-trunk-hook-variants": [
    "/catalog/gallery-trunk-hook-variants-view-02.jpg",
    "/catalog/gallery-trunk-hook-variants-view-03.jpg",
    "/catalog/gallery-trunk-hook-variants-view-04.jpg",
    "/catalog/gallery-trunk-hook-variants-view-05.jpg"
  ],
  "tesla-under-screen-storage-tray": [
    "/catalog/gallery-under-screen-storage-view-02.jpg",
    "/catalog/gallery-under-screen-storage-view-03.jpg",
    "/catalog/gallery-under-screen-storage-view-04.jpg",
    "/catalog/gallery-under-screen-storage-view-05.jpg"
  ],
  "tesla-under-seat-air-vent-cover-set": [
    "/catalog/gallery-under-seat-air-vent-covers-view-02.jpg",
    "/catalog/gallery-under-seat-air-vent-covers-view-03.jpg",
    "/catalog/gallery-under-seat-air-vent-covers-view-04.jpg",
    "/catalog/gallery-under-seat-air-vent-covers-view-05.jpg"
  ]
};

export function getProductGallery(slug: string) {
  return productGalleries[slug] ?? [];
}
